# GitLab pipeline used to build and push the image of each microservices.
#
# Copyright (c) 2022-2023, Tre Acque.
#
# This file is part of Tre Acque.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.

# Buildah is used to build and push the images.
image: quay.io/buildah/stable

stages:
  - build

variables:
  # Required because Docker uses overlayfs by default, Buildah cannot stack
  # overlayfs on top of another. This may be useless with newer version of
  # Buildah.
  STORAGE_DRIVER: vfs
  # Write image's metadata in the docker format, not standard OCI format. This
  # may be useless with newer version of Docker.
  BUILDAH_FORMAT: docker
  # Build images only in a chroot isolation, because we are already running
  # whithin a container.
  BUILDAH_ISOLATION: chroot

build-fountain-service:
  stage: build
  rules: # Buld and push only on default branch.
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}/fountain-service:${CI_COMMIT_SHORT_SHA}"
  before_script: # Authenticate Buildah to push on the private registry.
    - export REGISTRY_AUTH_FILE=${HOME}/auth.json
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah build --tag $IMAGE_NAME --file fountain-service/Dockerfile fountain-service
    - buildah push $IMAGE_NAME

build-notification-service:
  stage: build
  rules: # Buld and push only on default branch.
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}/notification-service:${CI_COMMIT_SHORT_SHA}"
  before_script: # Authenticate Buildah to push on the private registry.
    - export REGISTRY_AUTH_FILE=${HOME}/auth.json
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah build --tag $IMAGE_NAME --file notification-service/Dockerfile notification-service
    - buildah push $IMAGE_NAME

build-rating-service:
  stage: build
  rules: # Buld and push only on default branch.
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}/rating-service:${CI_COMMIT_SHORT_SHA}"
  before_script: # Authenticate Buildah to push on the private registry.
    - export REGISTRY_AUTH_FILE=${HOME}/auth.json
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah build --tag $IMAGE_NAME --file rating-service/Dockerfile rating-service
    - buildah push $IMAGE_NAME
