version: "3.9"
services:
  kafka:
    image: bitnami/kafka:3.3.1-debian-11-r29
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - app-net

  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop:3.27.0
    ports:
      - "9000:9000"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    networks:
      - app-net

  postgres:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    networks:
      - app-net
    restart: unless-stopped

  redis:
    image: redis:7.0.7
    ports:
      - "6379:6379"
    networks:
      - app-net
    restart: unless-stopped

  fountain-service:
    depends_on:
      - postgres
      - kafka
    build:
      context: ./fountain-service
      dockerfile: ./Dockerfile
    image: tre-acque/fountain-service
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      JDBC_URL: jdbc:postgresql://postgres:5432/app
      KAFKA_HOST: kafka:9092
    ports:
      - "8080:8080"
    networks:
      - app-net
    restart: unless-stopped

  notification-service:
    depends_on:
      - kafka
      - redis
    build:
      context: ./notification-service
      dockerfile: ./Dockerfile
    image: tre-acque/notification-service
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - MAILGUN_FROM=treacque@mailinator.com
      - MAILGUN_DOMAIN=sandbox7d41571d706b41b3bee12f9fc7684f64.mailgun.org
      - MAILGUN_API_KEY=YOUR_API_KEY
    ports:
      - "8081:3000"

  arangodb:
    image: arangodb:3.10
    environment:
      ARANGO_NO_AUTH: 1
    ports:
      - "8529:8529"
    networks:
      - app-net
    restart: unless-stopped

networks:
  app-net:
