= Tra Acque

Progetto di Cloud Computing (WIP).

== Deploy

Per fare il deploy usiamo il workflow GitOps in versione pull: https://www.gitops.tech/

È necessario configurare un cluster Kubernetes in modo appropriato come di
seguente.

=== Cluster minikube

È necessario fermare ed eliminare un cluster k8s se già attivo. Il motivo è che
bisogna creare un nuovo cluster con più CPU e memoria RAM assegnata.

```
$ minikube stop
$ minikube delete
$ minikube start --cpus 3 --memory 5000
```

Bisogna abilitare il componente aggiuntivo `ingress`, perché verrà utilizzato
dal servizio delle fontanelle:

```
$ minikube addons enable ingress
```

=== Credenziali d'accesso per il registry privato GitLab

Durante il deploy Kubernetes scaricherà le immagini dei servizi dal registro
privato associato alla repository su GitLab. Per questo motivo è necessario
fornire le credenziali come mostrato di seguito riportato dalla documentazione
ufficiale:
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-by-providing-credentials-on-the-command-line

Si assume che l'utente abbia generato un token personale (o un token di
progetto) dalla UI di GitLab con almeno il permesso `read-registry` . Si assume
inoltre di operare sul namespace `default` (usato anche dal deploy).

```
kubectl create secret docker-registry gitlab-credentials \
    --docker-server=registry.gitlab.com \
    --docker-username=GITLAB_USERNAME \
    --docker-password=GITLAB_TOKEN \
    --docker-email=GITLAB_EMAIL
```

Dove:

* `GITLAB_USERNAME` è il nome utente di chi genera il token;
* `GITLAB_TOKEN` è il token generato da GitLab;
* `GITLAB_EMAIL` è l'email associata all'utente che genera il token.

Poiché queste configurazioni vanno fatte una sola volta, e all'inizio della
creazione del cluster, si è deciso di non salvare questi manifesti nella
repository.

I manifesti dei singoli servizi hanno le immagini che puntano alla registro
privato, ma non viene specificato dove recuperare le credenziali per l'accesso.
Ecco perché, per ultimare, è necessario riferire al segreto appena creato:

```
kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "gitlab-credentials"}]}'
```

=== Aggiunta e configurazione dell'agente GitLab

Per installare l'agente sul cluster k8s viene utilizzato in via eccezionale
Helm, che va però installato sulla VM in cui si esegue il cluster. I comandi di
seguito sono riportati dalla documentazione ufficiale (per Debian): https://helm.sh/docs/intro/install/

```
$ curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
$ sudo apt-get install apt-transport-https --yes
$ echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
$ sudo apt-get update
$ sudo apt-get install helm
```

La sequente repository già fornisce un agente collegato che si può trovare al
percorso `.gitlab/agents/tre-acque-petriglia` con la relativa configurazione.
Poiché tale agente è privato, se si vuole provare il deploy è necessario creare
un'altra cartella con un altro nome e all'interno il file (anche vuoto)
`config.yaml`.

Ora è necessario dalla UI di GitLab generare il token relativo per l'agente
specificato (in questo caso si presume sia `tre-acque-petriglia`. Dalla stessa
UI GitLab suggerisce i comandi per installare e configurare l'agente, riportati
qui di seguito:

```
$ helm repo add gitlab https://charts.gitlab.io
$ helm repo update
helm upgrade --install AGENT_NAME gitlab/gitlab-agent \
    --namespace NAMESPACE \
    --create-namespace \
    --set image.tag=v15.8.0 \
    --set config.token=TOKEN \
    --set config.kasAddress=wss://kas.gitlab.com
```

Dove:

* `AGENT_NAME` è il nome dell'agente, in questo caso `tre-acque-petriglia`;
* `NAMESPACE` è il namespace di k8s in cui installare l'agente, in questo caso è
  `gitlab-agent-tre-acque-petriglia`;
* `TOKEN` è il token segreto di connessione, fornito dalla UI di GitLab.

Si suggerisce di usare un namespace diverso da `default`, perché in quest'ultimo
verrà effettuato il deploy dell'applicazione.

A questo punto l'agente è configurato ed è già in esecuzione, appena possibile,
in base alla configurazione presente nel file `config.yaml`, farà il deploy
dell'applicazione. Si possono monitorare gli eventi dell'agente andando a vedere
i log del pod associato con il seguente comando:

```
$ kubectl logs --follow NOME_POD --namespace NAMESPACE
```

Rimpiazzando ovviamente le variabili con i giusti valori dell'agente.

Una volta che il deploy si è stabilizzato, è possibile fare una prova tramite
cURL. Prima bisogna ottenere l'IP del gateway con `kubectl get ingress`.

```
$ kubectl get ingress
NAME       CLASS   HOSTS   ADDRESS        PORTS   AGE
fountain   nginx   *       192.168.49.2   80      69m

$ curl -i 192.168.49.2/fountains
HTTP/1.1 200 OK
Date: Thu, 26 Jan 2023 16:44:31 GMT
Content-Type: application/json
Content-Length: 2
Connection: keep-alive

[]
```

== Test con `curl`

1. Aggiunta di una fontana di nome "Fontana Via Armando Diaz" e in delle
   specifiche coordinate:

```
studente@ML-RefVm-605006:~$ curl -i -X POST 192.168.49.2/fountains -H "Content-Type: application/json" -d '{"name": "Fontana Via Armando Diaz", "latitude": 345.91341, "longitude": 315.9123}'
HTTP/1.1 201 Created
Date: Thu, 26 Jan 2023 09:43:15 GMT
Content-Type: application/json
Content-Length: 121
Connection: keep-alive
Location: http://192.168.49.2/fountains/id

{"id":"6f13307c-2bdc-40da-ba72-862bf2fddad7","name":"Fontana Via Armando Diaz","latitude":345.91341,"longitude":315.9123}
```

2. Elenco di tutte le fontane:

```
studente@ML-RefVm-605006:~$ curl -i 192.168.49.2/fountains
HTTP/1.1 200 OK
Date: Thu, 26 Jan 2023 09:44:15 GMT
Content-Type: application/json
Content-Length: 225
Connection: keep-alive

[{"id":"d61bcdb4-1b7b-4e0b-a438-172a9f5f245f","name":"Test","latitude":345.91341,"longitude":315.9123},{"id":"6f13307c-2bdc-40da-ba72-862bf2fddad7","name":"Fontana Via Armando Diaz","latitude":345.91341,"longitude":315.9123}]
```

3. Aggiunta di un voto alla fontana "Fontana Via Armando Diaz" con valore 5:

```
studente@ML-RefVm-605006:~$ curl -i -X POST 192.168.49.2/fountains/6f13307c-2bdc-40da-ba72-862bf2fddad7/rating -H "Content-Type: application/json" -d 5
HTTP/1.1 201 Created
Date: Thu, 26 Jan 2023 09:45:56 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 55
Connection: keep-alive

{"id":"3afc0b19-9d5e-11ed-8276-0242ac11000c","value":5}
```

4. Ottenimento del singolo voto:

```
studente@ML-RefVm-605006:~$ curl -i 192.168.49.2/fountains/6f13307c-2bdc-40da-ba72-862bf2fddad7/rating/3afc0b19-9d5e-11ed-8276-0242ac11000c
HTTP/1.1 200 OK
Date: Thu, 26 Jan 2023 09:46:44 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 55
Connection: keep-alive

{"id":"3afc0b19-9d5e-11ed-8276-0242ac11000c","value":5}
```

5. Dopo l'aggiunta di un secondo voto alla stessa fontana di valore 2, si
   ottiene la media dei voti per la fontana (valore approssimato per eccesso):

```
studente@ML-RefVm-605006:~$ curl -i 192.168.49.2/fountains/6f13307c-2bdc-40da-ba72-862bf2fddad7/rating
HTTP/1.1 200 OK
Date: Thu, 26 Jan 2023 09:48:15 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 1
Connection: keep-alive

4
```

6. Eliminazione di un voto:

```
studente@ML-RefVm-605006:~$ curl -i -X DELETE 192.168.49.2/fountains/6f13307c-2bdc-40da-ba72-862bf2fddad7/rating/3afc0b19-9d5e-11ed-8276-0242ac11000c
HTTP/1.1 200 OK
Date: Thu, 26 Jan 2023 09:49:38 GMT
Content-Length: 0
Connection: keep-alive

```

7. Ciò ovviamente comporta il cambiamento della media dei voti per la fontana (è
   presente un unico valore 2):

```
studente@ML-RefVm-605006:~$ curl -i 192.168.49.2/fountains/6f13307c-2bdc-40da-ba72-862bf2fddad7/rating
HTTP/1.1 200 OK
Date: Thu, 26 Jan 2023 09:50:12 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 1
Connection: keep-alive

2
```

8. Eliminazione di una fontana.

TODO

9. Eliminare una fontana comporta anche l'eliminazione dei voti

TODO




