apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: tre-acque
build:
  artifacts:
    - image: fountain-service
      context: ./fountain-service
      docker:
        dockerfile: Dockerfile
    - image: notification-service
      context: ./notification-service
      docker:
        dockerfile: Dockerfile
    - image: rating-service
      context: ./rating-service
      docker:
        dockerfile: Dockerfile
  local:
    push: false
    concurrency: 0 # no-limit
manifests:
  rawYaml:
    - ./k8s/dev/**/*.yaml
deploy:
  tolerateFailuresUntilDeadline: true
  kubectl: {}
