apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: tre-acque
build:
  artifacts:
    - image: tre-acque/fountain-service
      context: ./fountain-service
      docker:
        dockerfile: Dockerfile
    - image: tre-acque/notification-service
      context: ./notification-service
      docker:
        dockerfile: Dockerfile
  local:
    push: false
    concurrency: 0 # no-limit
manifests:
  rawYaml:
    - ./k8s/**/postgis.yaml
    - ./k8s/**/kafka.yaml
    - ./k8s/**/fountain-service.yaml
    - ./k8s/**/redis.yaml
    - ./k8s/**/notification-service.yaml
deploy:
  tolerateFailuresUntilDeadline: true
  kubectl: {}
