apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app.kubernetes.io/name: frontend-service
    app.kubernetes.io/instance: frontend-service-1
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: frontend-service
    app.kubernetes.io/part-of: tre-acque
    app.kubernetes.io/managed-by: Kubernetes
spec:
  selector:
    app.kubernetes.io/name: frontend-service
    app.kubernetes.io/instance: frontend-service-1
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
