apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: kafka-1
    app.kubernetes.io/version: "3.11-alpine"
    app.kubernetes.io/component: message-broker
    app.kubernetes.io/part-of: tre-acque
    app.kubernetes.io/managed-by: Kubernetes
spec:
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: kafka-1
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 9092
      targetPort: http
      protocol: TCP