apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend
  namespace: default
spec:
  encryptedData:
    apikey: AgCL7mx6L1P1Iv+zFYs31mALoZHdSqQahCn/HJr7UDRt1sKAnmlFL6GEoFUKSEgQqwRZ8UYLc18ENIte5tlbSwr/cKdIaetoILITlsmZeFAA9JMEH9Vrqp2Cxqr65lpROQb8Tjdjz9efE05BCLaKnWJurWNFxVkL2okGAkLFJSTHg4oG2kE6vzxaVXgwfhwK5YJiMaYyLg7NfVQgn0L0BZdI+aBNhXz3/Ar+muM4dBcomjepaWwJ+Dqw4rMuswry9QyUV8j36DQhtKYBlgyQw+Ra8J2G4kGbRePSf0zIWaNrlWXQou8rbE6BYs8q4g90T4KAqAS9IFy90KtcaR+BBhduiGmqqyQhCMGsKPbyBs/KJGExkTnBtRaY7PQOAQABh4wUzM/Cw9rtGU3nPss1azXg2gX/vWYw18U36dYhnTJT+7TuRcBlat5pA3d1O4Sb+AB6lUaPbyeBCQ06EREZFB5wHRAd67rkS+misqvypVtChFtX2NypL6N8NyZoo8wkBFTv9/9p+6k692AFaNh8oP0b9WmK7HENndd1rsfvDS+hciJ+vJjVfq8nKfQCOvveMeN/D8RwseLKxZZED7FYJgsJ9QuWRr8+f1Cbs4p96SaiwxEnnkr+0unP1zXZSHs078R1jZwB03rdzh1iXpO+By8HoOdgo0yTxttBlXDjOxsvdpplaCOeV7hwcnos8U7OyV9k8a1uQSs1Cquki/Wb1mB+buucRcrsrRs+iFia6wame1pxbO6lSqKq3F+Ka7a0IuJINko0Uz6DTNK2NtpfJP1WIkob+HUdSdu3qHlU/W0j/iqCYbwULBKGzh2v8xphbK6U/Xwh
  template:
    metadata:
      name: frontend
      namespace: default
