apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres
  namespace: default
spec:
  encryptedData:
    password: AgAl7oYtGiUkS9ayrUWfPlKWD/6BLPPYWU0T/bis096GIRTiQQg7YX+uQtOoKHA+3EHL5bOlAmHLYV425jPPOCLkCQwyjroxyUbxFubM7T5lsH6kOuzya9zubDzuqRFuZWaSiHSo94JcCERU89ah7JtrCtz/JbPEcEhAfPYq/jL6ilzZKU8XBg6lWs2Q06gHyD2jE0Gm6wQTd96CU327ppN5nMUBg+T8gxO3b4eZnI67PQ33HN6Sl84YnVyAVGyD9a7zZZK185Ybws8kQixo/FDuB9c6tU2oJHx60Ix98mVZUBiOU6df3ghzGvki3cb45uAZveVTieDQTtfq7diIP8U20jspo2lVtgdMyD/ynKUrF3bEKgjv0UbgPJUCfmTH5Z9YjY3iQwW7BV5BtkacFhAWiFzqYLbAmyAqyzYzxgwcI5BxuUykpPGCx8ULABXMmf69sv6p6c4s8tcAkTe0cqhq1cCv7zxxG7KzxIbCpOTFzuTRdPar0eDd4hzwu2MIcDwfG0aCI6Yi5bgQyfOUeMa/44omA4X9H0bk0AB0qj9/3FYuu0aaGEFNlUQjL6Gye/Bo3mF92MT4O0ArgInojkaE8VjU0jK+TDhz160hBx4CU2zXqvOJ2fvLcIarHYT5Sb/IlnfmG0tJ0bwjuS92Wud0vLO/9e/VcLkMq4oQhGdj5nImemUsNszBmUocsg+TY7YQqPeS3pQLew==
  template:
    metadata:
      name: postgres
      namespace: default

