apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis
  namespace: default
spec:
  encryptedData:
    password: AgCdXwAwNeCMYDy2VbYaKR7OqdoaqX6cX7kDHwyz9aRqZSwpftc1vyPJlIbHjUAILOFnWSYTkxXEof9RKe6zUybzVXdpu2a57fMeulvHMDfQXLUHeS/piFxI6WdZw/IXe+3H6IRW17FJK3OK3LjKQG7oYjCmYQxV7HcwopegnAgaZaYAhAIIs4FaHzuCygpWjA+/xTIXeZlb/eW2v1E7CmYI1/tOQ96KNG7ocfLY7okeu2YUjugLUYxjNEh63UVlCdD/GAVIjUGY68Yl1Ehm+bBVUrIsRR1Gvp9FiH79uCk3noB2ehUfji2wG501sI/FY2PePqF7mYh826LG99kI1ZGuzgHL8ny80p2NvCL3OI+PyGqt3DxsklTNxaI5Gbuc3lnlGnIed41KLu6Pg+e3t6ZkWDSXVJI4riLe68cAlHdSXymoBSHt90DnXVit5YCha4BKRpwTHVAgEveetBjsU9beYdlqE5dCz/skMH+pF/A1UnDuuQLa25OYWKctWHgxjspu+6x8/RYPwnQ4FzkBGIJTx1vdo2zsNhDI/kxRfZzCC6tL+4PtSp8H5I4A2GOYulBt67dPOULwaAiC9+kC1uoQrSlWEJHEQPUwo2ZQ0wMwZlME85Qh18fAWufGqk2brCjUxgBsNvWMUHK++EUZAc6b6jrRW4EU4Czn99MXoT3qzdQ0Ldjiwz93pa/YUokF70jc8cSsh85UMwE=
  template:
    metadata:
      creationTimestamp: null
      name: redis
      namespace: default

