apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
  namespace: default
spec:
  encryptedData:
    password: AgCyrfI7mqcBs23aAsqmjBDFNmz/eRYrvn+c80QrxI93bXkDax+I65TILGQh06a68wrKtHMZZb1QnK420L57PCHSFJsmw++2wA+qZE9dOTovNrAPr5TPRHc4UifrvIDQ7KTvfXeAOIYQe2LnHDCEMp6QGY2LnXeZ46VwJ6b/B54bh/+IUjhEnr0N155FEAL+vBYmtlJ18qfcv0g57ikRVYKwJjtxVLkgMX8J3LI+HQb5MQ8bPPGP5mYPaJnwZQ+E2TAr5lz/SDuDQMDe5BB/ps4JB079gKu0D6AGTCxcFZXuNfwk3KnzEFTVHorbCYe2jT/aFkp5dMtI1B4TjcTiDheYYI9M0h2sY9nvUUlIDR1Dj7wmPfPYLErlkN1KDB+nbWVYfIWy25NCP+sO0VKiST/PUJGeAgLtNtfCjcJ+OtO7zV7IAe6+O6V49j83QFzLYkqS9hjKBV2VzgMFo+keo/TMALclSid5h/PymBC2fp4ff27MmHjs0hHTIBuElmaKS+YySvYlUv+c4eODvzx8fgs4hzy9//+LOi22Q22otBJHGLfTIF0SIPYJPZwlvG+2gZ+xK7tII4ULJXg+GA8+Q3NPVe+gW6MG89iL2vKSYAffPmqCLrWUC8fJ1EODEDl9HP+bpWu4YXFpw+4kZzF0Fs7CE5kKBQi+udLXG2Wtooa0YNGqpkZ7twXgQ/fujDu8zbNN2K+LuOzHn08+OsI=
  template:
    metadata:
      name: redis
      namespace: default

