apiVersion: v1
kind: Secret
metadata:
  name: frontend
  namespace: default
data:
  # Dummy key "BASE64API_KEY". You can use 'echo -n KEY | base64 -w 0' to
  # generate the data.
  apikey: QkFTRTY0QVBJX0tFWQ==
