apiVersion: v1
kind: Secret
metadata:
  name: mailgun
  namespace: default
data:
  # Dummy values. You can use 'echo -n DATA | base64 -w 0' to generate the data.
  from: QkFTRTY0QVBJX1ZBTFVF
  domain: QkFTRTY0QVBJX1ZBTFVF
  apikey: QkFTRTY0QVBJX1ZBTFVF
