apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  labels:
    app.kubernetes.io/name: frontend-service
    app.kubernetes.io/instance: frontend-service-1
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: frontend-service
    app.kubernetes.io/part-of: tre-acque
    app.kubernetes.io/managed-by: Kubernetes
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend-service
      app.kubernetes.io/instance: frontend-service-1
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend-service
        app.kubernetes.io/instance: frontend-service-1
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: frontend-service
          image: registry.gitlab.com/tre-acque/tre-acque/frontend-service:2f6c605e
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: frontend
                  key: apikey
            - name: FOUNTAIN_SERVICE_API
              value: tre-acque.com
            - name: NOTIFICATION_SERVICE_API
              value: tre-acque.com
            - name: RATING_SERVICE_API
              value: tre-acque.com
