apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service
  labels:
    app.kubernetes.io/name: rating-service
    app.kubernetes.io/instance: rating-service-1
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: rating-service
    app.kubernetes.io/part-of: tre-acque
    app.kubernetes.io/managed-by: Kubernetes
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rating-service
      app.kubernetes.io/instance: rating-service-1
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rating-service
        app.kubernetes.io/instance: rating-service-1
    spec:
      containers:
        - name: rating-service
          image: registry.gitlab.com/tre-acque/tre-acque/rating-service:1a30428b
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ARANGODB_URL
              value: tcp://arangodb:8529
            - name: ARANGODB_DB
              value: ratingsdb
            - name: ARANGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: arangodb
                  key: password
            - name: KAFKA_URL
              value: kafka:9092
            - name: KAFKA_GROUPID
              value: rating-service
            - name: KAFKA_TOPIC
              value: fountain_events
            - name: SERVER_PORT
              value: "8080"
          resources:
            limits:
              cpu: 0.2
              memory: 200Mi
          livenessProbe:
            httpGet:
              port: 8080
              path: /liveness
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: /readiness
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 2




