apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fountain
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    # It accepts connections from every hosts, not only "tre-acque.com"
    - http:
        paths:
          - path: /subscribe
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  name: http
          - path: /unsubscribe
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  name: http
          - path: /fountains/(.+)/rating
            pathType: Prefix
            backend:
              service:
                name: rating-service
                port:
                  name: http
          - path: /fountains
            pathType: Prefix
            backend:
              service:
                name: fountain-service
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  name: http
 
