openapi: 3.0.3
info:
  title: Tre Acque
  description: To insert
  contact:
    name: Tre Acque
    url: https://gitlab.com/tre-acque
    email: v.corso3@campus.unimib.it
  license:
    name: AGPL
    url: https://gitlab.com/tre-acque/tre-acque/LICENSE.md
  version: "1"
servers:
  - url: http://localhost:8080
paths:
  /fountains:
    get:
      description: Gets all the fountains
      parameters:
      - name: area
        description: The optinal search area
        in: query
        required: false
        schema:
          type: object
          required:
          - latitude
          - longitude
          properties:
            latitude:
              type: number
              format: double
            longitude:
              type: number
              format: double
            radius:
              type: number
              format: double
              default: 500.0
        examples:
          with radius:
            value:
              latitude: 543.13
              longitude: 654.123
              radius: 340.50
          without radius:
            value:
              latitude: 543.13
              longitude: 654.123
      responses:
        200:
          description: The list of fountains was successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FountainResponse"
    post:
      description: Add a new fountain
      requestBody:
        description: The fountain details
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - name
              - latitude
              - longitude
              properties:
                name:
                  type: string
                latitude:
                  type: number
                  format: double
                longitude:
                  type: number
                  format: double
              example:
                name: Fontana Via Armando Diaz
                latitude: 345.91341
                longitude: 315.9123
      responses:
        201:
          description: The fountain was successfully added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FountainResponse"
        400:
          description: The request is not valid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                type: "VALIDATION_ERROR"
                message: "There was an error during the validation of the request"
                issues:
                - "The latitude of the fountain must be present"
                - "The longitude of the fountain must be present"
  /fountains/{fountainId}:
    parameters:
    - name: fountainId
      description: the fountain id
      in: path
      required: true
      schema:
        type: string
      example: 1
    get:
      description: Get the fountain with the given id
      responses:
        200:
          description: The fountain was successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FountainResponse"
        404:
          description: The fountain with the given id was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                type: "NOT_FOUND_ERROR"
                message: "The entity with the given id (1) was not found"
                issues: []
    delete:
      description: Delete the fountain with the given id
      responses:
        200:
          description: The fountain with the given id was succefully deleted
        404:
          description: The fountain with the given id was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                type: "NOT_FOUND_ERROR"
                message: "The entity with the given id (1) was not found"
                issues: []
components:
  schemas:
    ErrorResponse:
      type: object
      description: The payload returned when one or more errors occur
      properties:
        type:
          type: string
        message:
          type: string
        issues:
          type: array
          items:
            type: string
      example:
        type: VALIDATION_ERROR
        message: There was an error during the validation of the request
        issues:
        - The query parameters longitude and latitude must be both present or both absent
    FountainResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
      example:
        id: 1
        name: Fontana Via Armando Diaz
        latitude: 345.91341
        longitude: 315.9123