openapi: 3.0.3
info:
  title: Tre Acque
  description: To insert
  contact:
    name: Tre Acque
    url: https://gitlab.com/tre-acque
    email: v.corso3@campus.unimib.it
  license:
    name: AGPL
    url: https://gitlab.com/tre-acque/tre-acque/LICENSE.md
  version: "1"
servers:
  - url: http://localhost:8080
paths:
  /fountains:
    get:
      description: Gets all the fountains
      parameters:
      - name: area
        description: The search area
        in: query
        required: false
        schema:
          type: object
          required:
          - latitude
          - longitude
          properties:
            latitude:
              type: number
              format: double
            longitude:
              type: number
              format: double
            radius:
              type: number
              format: double
              default: 500.0
        examples:
          with radius:
            value:
              latitude: 543.13
              longitude: 654.123
              radius: 340.50
          without radius:
            value:
              latitude: 543.13
              longitude: 654.123
      - name: latitude
        description: The centre latitude
        in: query
        required: false
        schema:
          type: number
          format: double
        example: 132.541231
      - name: longitude
        description: The centre longitude
        in: query
        required: false
        schema:
          type: number
          format: double
        example: 412.123141
      - name: radius
        description: The search radius (in meters)
        in: query
        required: false
        schema:
          type: number
          format: double
          default: 500.0
      responses:
        200:
          description: The list of fountains was successfully retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  latitude:
                    type: number
                    format: double
                  longitude:
                    type: number
                    format: double
                example:
                  id: 1
                  name: Fontana Via Armando Diaz
                  latitude: 345.91341
                  longitude: 315.9123
    post:
      description: Add a new fountain
      requestBody:
        description: The fountain details
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - name
                latitude
                longitude
              properties:
                name:
                  type: string
                latitude:
                  type: number
                  format: double
                longitude:
                  type: number
                  format: double
              example:
                name: Fontana Via Armando Diaz
                latitude: 345.91341
                longitude: 315.9123
      responses:
        201:
          description: The fountain was successfully added
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  latitude:
                    type: number
                    format: double
                  longitude:
                    type: number
                    format: double
                example:
                  id: 1
                  name: Fontana Via Armando Diaz
                  latitude: 345.91341
                  longitude: 315.9123
        400:
          description: The request is not valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  message:
                    type: string
                  issues:
                    type: array
                    items:
                      type: string
  /fountains/{fountainId}:
    parameters:
    - name: fountainId
      description: the fountain id
      in: path
      required: true
      schema:
        type: string
      example: 1
    get:
      description: Get the fountain with the given id
      responses:
        200:
          description: The fountain was successfully retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  latitude:
                    type: number
                    format: double
                  longitude:
                    type: number
                    format: double
                example:
                  id: 1
                  name: Fontana Via Armando Diaz
                  latitude: 345.91341
                  longitude: 315.9123
        404:
          description: The fountain with the given id was not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  message:
                    type: string
    delete:
      description: Delete the fountain with the given id
      responses:
        200:
          description: Delete the fountain with the given id
        404:
          description: The fountain with the given id was not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  message:
                    type: string