apiVersion: v1
kind: Service
metadata:
  name: rating-service
  labels:
    app.kubernetes.io/name: rating-service
    app.kubernetes.io/instance: rating-service-1
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: rating-service
    app.kubernetes.io/part-of: tre-acque
    app.kubernetes.io/managed-by: Kubernetes
spec:
  selector:
    app.kubernetes.io/name: rating-service
    app.kubernetes.io/instance: rating-service-1
  type: ClusterIP
  ports:
    - name: http
      port: 8082
      targetPort: http
