gitops:
  # List of repositories where k8s manifests are stored. In our case there is
  # only one repository with both manifests and code.
  manifest_projects:
    - id: tre-acque/tre-acque
      ref:
        branch: master # Watch manifests on default branch.
      default_namespace: default # k8s namespace
      paths:
        - glob: 'k8s/**/*.yaml'
      reconcile_timeout: 900s # Wait max 15 minutes k8s to apply the changes.
      prune_timeout: 900s
