apiVersion: apps/v1
kind: Deployment
metadata:
  name: fountain-service
  labels:
    app.kubernetes.io/name: fountain-service
    app.kubernetes.io/instance: fountain-service-1
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: fountain-service
    app.kubernetes.io/part-of: tre-acque
    app.kubernetes.io/managed-by: Kubernetes
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fountain-service
      app.kubernetes.io/instance: fountain-service-1
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fountain-service
        app.kubernetes.io/instance: fountain-service-1
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: fountain-service
          image: registry.gitlab.com/tre-acque/tre-acque/fountain-service:2f6c605e
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              value: postgis
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: app
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: KAFKA_HOST
              value: kafka:9092
          resources:
            limits:
              cpu: 0.5
              memory: 200Mi
          livenessProbe:
            httpGet:
              port: 8080
              path: /q/health/live
            initialDelaySeconds: 30
            timeoutSeconds: 20
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              port: 8080
              path: /q/health/ready
            initialDelaySeconds: 25
            timeoutSeconds: 20
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
