apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/instance: notification-service-1
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: notification-service
    app.kubernetes.io/part-of: tre-acque
    app.kubernetes.io/managed-by: Kubernetes
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: notification-service
      app.kubernetes.io/instance: notification-service-1
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: notification-service
        app.kubernetes.io/instance: notification-service-1
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: notification-service
          image: tre-acque/notification-service
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_USER
              value: admin
            - name: RABBITMQ_PASSWORD
              value: password
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_HOST
              value: redis
            - name: MAILGUN_FROM
              value: treacque@mailinator.com
            - name: MAILGUN_DOMAIN
              value: sandbox7d41571d706b41b3bee12f9fc7684f64.mailgun.org
            - name: MAILGUN_API_KEY
              value: YOUR_API_KEY
          resources:
            limits:
              cpu: 0.5
              memory: 200Mi
          livenessProbe:
            httpGet:
              port: 3000
              path: /live
            initialDelaySeconds: 15
            timeoutSeconds: 20
            periodSeconds: 20
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              port: 3000
              path: /ready
            initialDelaySeconds: 10
            timeoutSeconds: 20
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
# TODO: add rolling updates strategy
