apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: rabbitmq-1
    app.kubernetes.io/version: "3.11-alpine"
    app.kubernetes.io/component: message-broker
    app.kubernetes.io/part-of: tre-acque
    app.kubernetes.io/managed-by: Kubernetes
spec:
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: rabbitmq-1
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 5672
      targetPort: http
      protocol: TCP