apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgis
  labels:
    app.kubernetes.io/name: postgis
    app.kubernetes.io/instance: postgis-1
    app.kubernetes.io/version: "15-3.3"
    app.kubernetes.io/component: fountain-service-db
    app.kubernetes.io/part-of: fountain-service
    app.kubernetes.io/managed-by: Kubernetes
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
