apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-1
    app.kubernetes.io/version: "7.0.7"
    app.kubernetes.io/component: notification-service-db
    app.kubernetes.io/part-of: notification-service
    app.kubernetes.io/managed-by: Kubernetes
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
